name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --verbose
